Repository nucleos/NucleosUserAdminBundle, pull requests merged in 2021-12, with the labels that each got.

#415 Use Asset for DefaultAvatar Url
  composer.json
  src/Avatar/StaticAvatarResolver.php
  src/Resources/config/avatar.php
Labels: Enhancement

#407 Drop PHP 7 support
  .github/settings.yml
  .github/workflows/continuous-integration.yml
  composer.json
  vendor-bin/tools/composer.json
Labels: Enhancement

#419 Bump symfony 5.4
  .github/settings.yml
  .github/workflows/continuous-integration.yml
  composer.json
  phpstan-baseline.neon
  psalm-baseline.xml
  src/Form/Transformer/RestoreRolesTransformer.php
  tests/Action/IntegrationTestCase.php
  tests/Action/LoginActionTest.php
  tests/App/AppKernel.php
  tests/App/Entity/User.php
  tests/App/config/config.php
  tests/Form/Transformer/RestoreRolesTransformerTest.php
Labels: dependency

#420 Fix admin group translation
  src/Admin/Model/GroupAdmin.php
  src/Admin/Model/UserAdmin.php
  src/Resources/translations/NucleosUserAdminBundle.de.xlf
  src/Resources/translations/NucleosUserAdminBundle.en.xlf
Labels: Bug

#432 Remove composer-bin plugin
  .github/workflows/continuous-integration.yml
  composer.json
Labels: Enhancement

#435 Remove deprecations
  src/Resources/config/action.php
  src/Resources/config/admin.php
  src/Resources/config/admin_mongodb.php
  src/Resources/config/admin_orm.php
  src/Resources/config/avatar.php
  src/Resources/config/impersonating.php
  src/Resources/config/security_acl.php
  src/Resources/config/twig.php
  tests/App/Entity/User.php
Labels: Enhancement

#443 Bump nucleos/user-bundle
  composer.json
  phpstan-baseline.neon
  src/Action/ResetAction.php
  src/Action/SendEmailAction.php
  src/Admin/Model/GroupAdmin.php
  src/Admin/Model/UserAdmin.php
  src/Resources/config/action.php
  tests/Action/ResetActionTest.php
  tests/Action/SendEmailActionTest.php
  tests/Admin/Entity/GroupAdminTest.php
  tests/Admin/Entity/UserAdminTest.php
  tests/App/Entity/Group.php
  tests/App/Entity/User.php
  tests/App/config/config.php
Labels: dependency

#445 Remove all.php routing
  UPGRADE-3.0.md
  docs/index.rst
  docs/installation.rst
  docs/routing.rst
Labels: BC Break

#447 Remove all.php routing
  src/Resources/config/routing/all.php
Labels: BC Break
